apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeper-dev-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/emdadul38/argocd-app-config.git
    targetRevision: HEAD
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: veeper-dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
