apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    run: myapp
spec:
  selector:
    app: pod-myapp
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
